=== magben2/ProjetXML/ue.dtd
<?xml version="1.0" encoding="utf-8" ?>

<!ELEMENT master		(unite+, intervenant+, parcours)>
<!ELEMENT intervenant	(nom, mail, web)>
<!ELEMENT parcours		(responsable+, nom, description, debouche+, semestre+)>
<!ELEMENT semestre		(bloc-ue)>
<!ELEMENT unite			(nom, nbCredit, resume, plan, lieu, ref-intervenant+)>
<!ELEMENT bloc-ue		(ref-unite+)>

<!ELEMENT nom				(#PCDATA)>
<!ELEMENT mail				(#PCDATA)>
<!ELEMENT nbCredit			(#PCDATA)>
<!ELEMENT resume			(#PCDATA)>
<!ELEMENT plan				(#PCDATA)>
<!ELEMENT lieu				(#PCDATA)>
<!ELEMENT web				(#PCDATA)>
<!ELEMENT ref-intervenant 	(#PCDATA)>
<!ELEMENT responsable	 	(#PCDATA)>
<!ELEMENT description	 	(#PCDATA)>
<!ELEMENT debouche		 	(#PCDATA)>

<!ELEMENT p					(#PCDATA|(b|i|a)*)>
<!ELEMENT b					(#PCDATA)>
<!ELEMENT i					(#PCDATA)>
<!ELEMENT a					(#PCDATA)>
<!ELEMENT ul				(li+)>
<!ELEMENT li				(#PCDATA)>
<!ELEMENT table				(tr+)>
<!ELEMENT tr				(td+)>
<!ELEMENT td				(#PCDATA)>

<!ATTLIST bloc-ue 			role 	(obligatoire | option)		#REQUIRED>
<!ATTLIST unite 			id 		ID 			#REQUIRED>
<!ATTLIST intervenant 		id 		ID 			#REQUIRED>
<!ATTLIST responsable		id 		ID	 		#REQUIRED><!-- voir -->
<!ATTLIST ref-intervenant 	ref 	IDREF 		#REQUIRED>
<!ATTLIST ref-responsable	ref 	IDREF 		#REQUIRED><!-- voir -->
<!ATTLIST ref-unite			ref 	IDREF 		#REQUIRED><!-- voir -->

<!ATTLIST a		 			href	(#PCDATA) 	#REQUIRED>

<!ENTITY luminy 		"Luminy">
<!ENTITY stjerome 		"St-Jérôme">
<!ENTITY etoile 		"l'Étoile">
<!ENTITY mail.luminy	"@univ-amu.fr">
<!ENTITY dom.luminy		"univ-mrs.fr">
<!ENTITY dom.dil		"dil.&dom.luminy;">

=== magben2/ProjetXML/ue.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE master SYSTEM "ue.dtd">
<?xml-stylesheet type="text/xsl" href= "ue.xsl" ?>

<master>
	<intervenant id="agopian">
		<nom>Roland Agopian</nom>
		<mail>roland.agopian&mail.luminy;</mail>
		<web></web>
	</intervenant>
	
	<intervenant id="bechet">
		<nom>Frederic Bechet</nom>
		<mail>frederic.bechet&mail.luminy;</mail>
		<web></web>
	</intervenant>
	
	<intervenant id="boucelma">
		<nom>Omar Boucelma</nom>
		<mail>omar.boucelma&mail.luminy;</mail>
		<web></web>
	</intervenant>
	
	<intervenant id="broche">
		<nom>Martine Broche</nom>
		<mail>martine.broche&mail.luminy;</mail>
		<web></web>
	</intervenant>

	<intervenant id="chepoi">
		<nom>Victor Chepoi</nom>
		<mail>victor.chepoi&mail.luminy;</mail>
		<web></web>
	</intervenant>

	<intervenant id="contensin">
		<nom>Magali Contensin</nom>
		<mail>magali.contensin&mail.luminy;</mail>
		<web></web>
	</intervenant>
	
	<intervenant id="estellon">
		<nom>Bertrand Estellon</nom>
		<mail>bertrand.estellon&mail.luminy;</mail>
		<web></web>
	</intervenant>
	
	<intervenant id="godard">
		<nom>Emmanuel Godard</nom>
		<mail>emmanuel.godard&mail.luminy;</mail>
		<web></web>
	</intervenant>
	
	<intervenant id="massat">
		<nom>Jean-Luc Massat</nom>
		<mail>jean-luc.massat&mail.luminy;</mail>
		<web></web>
	</intervenant>

	<intervenant id="molin">
		<nom>Alain Dal Molin</nom>
		<mail>alain.dal-molin&mail.luminy;</mail>
		<web></web>
	</intervenant>
	
	<intervenant id="morin">
		<nom>Rémi Morin</nom>
		<mail>remi.morin&mail.luminy;</mail>
		<web></web>
	</intervenant>

	<intervenant id="niebert">
		<nom>Peter Niebert</nom>
		<mail>peter.niebert&mail.luminy;</mail>
		<web></web>
	</intervenant>

	<intervenant id="novelli">
		<nom>Noel Novelli</nom>
		<mail>noel.novelli&mail.luminy;</mail>
		<web></web>
	</intervenant>
	
	<intervenant id="sabatier">
		<nom>Claude Sabatier</nom>
		<mail>claude.sabatier&mail.luminy;</mail>
		<web></web>
	</intervenant>

	<intervenant id="santocanale">
		<nom>Luigi Santocanale</nom>
		<mail>luigi.santocanale&mail.luminy;</mail>
		<web></web>
	</intervenant>

	<intervenant id="das">
		<nom>Shantanu Das</nom>
		<mail>shantanu.das&mail.luminy;</mail>
		<web></web>
	</intervenant>

	<intervenant id="olive">
		<nom>Frederic Olive</nom>
		<mail>frederic.olive&mail.luminy;</mail>
		<web></web>
	</intervenant>


	<unite id=" ENSINCU27">
		<nom>Anglais 2</nom>
		<nbCredit>3</nbCredit>
		<resume>
			<p>Expression orale et écrite : exposés sur des sujets scientifiques et / ou professionnels, travaux écrits. Préparation et passage du TOEIC.</p>
		</resume>
		<plan></plan>
		<lieu>Luminy</lieu>
		
		<ref-intervenant ref="novelli"></ref-intervenant>
	</unite>
	
	<unite id="ENSINCU28">
		<nom>Communication 2</nom>
		<nbCredit>3</nbCredit>
		<resume><p>L’étudiant apprend à effectuer un bilan de son parcours de formation, à élaborer un projet professionnel personnel, à cerner ses motivations et à enrichir ses connaissances des métiers et du marché de l’informatique pour se constituer un portefeuille de compétences.</p>

		<ul>
			<li>Valorisation du parcours de formation</li>
			<li>Clarification des motivations et de leurs incidences sur des choix professionnels</li>
			<li>Identification des aptitudes et des compétences,</li>
			<li>Positionnement du projet personnel et professionnel</li>
			<li>Ajustement des profils annonce / candidature</li>
			<li>Préparation aux entretiens de recrutement</li>
			<li>Rédaction de curriculum vitae et de lettres de motivation</li>
		</ul>
	</resume>
		<plan></plan>
		<lieu>Luminy</lieu>
		
		<ref-intervenant ref="novelli"></ref-intervenant>
	</unite>
	
	<unite id="ENSINCU29">
		<nom>Fiabilité logicielle 1</nom>
		<nbCredit>3</nbCredit>
		<resume>
			<ul>
				<li>Introduction fiabilité vs sécurité</li>
				<li>Test boite blanche (graphe de contrôle, de donnée, mesure de couverture, modèle à base d'automates, qualité logicielle)</li>
				<li>Test boite noire (spécifications formelle informelles, construction de suite de tests : partitionnement, tests au limites, tests combinatoires, graphe de causalité)</li>
				<li>Test et Simulation (Objets factices, inversion de contrôle, intégration)</li>
				<li>Validation Formelle (système de preuves : Hoare, logique de séparation, analyse statique)</li>
			</ul>
			<p><b>Pre-Requis</b></p>
			<ul>
				<li>Environnement de programmation Eclipse</li>
				<li>Java</li>
			</ul>
		</resume>
		<plan></plan>
		<lieu>Luminy</lieu>
		
		<ref-intervenant ref="massat"></ref-intervenant>
	</unite>
	
	<unite id="ENSINCU30">
		<nom>Plateforme JEE</nom>
		<nbCredit>3</nbCredit>
		<resume><p>L'objet du cours est de présenter le développement d'applications dans le cadre de la plateforme JEE ( Java Enterprise Edition ). Nous étudions notamment</p>
			<p>Accès aux ressources extérieures :</p>
			<ul>
				<li>les interfaces java d'accès aux bases de données relationnelles (JDBC),</li>
				<li>les interfaces d'accès aux annuaires d'entreprise (LDAP, JNDI)</li>
			</ul>
			<p> Mise en place d'une couche métier (middleware) :</p>
			<ul>
				<li>les architectures logicielles à base de composants (EJB, Spring, Jboss, Glassfish) et les principes de mise en œuvre (spécification/implantation, injection de dépendances et inversion de contrôle),</li>
				<li>l'architecture des applications 3-tiers,</li>
			</ul>
			<p>Couche de présentation et interfaces Web :</p>
			<ul>
				<li>les technologies de mise en œuvre des applications WEB (Servlet, JSP, Tomcat, Glassfish).</li>
			</ul>
			<p><b>Pre-Requis</b></p>
			<ul>
				<li>XML / XPATH / XSLT</li>
				<li>Technologies du Web ((X)HTML, CSS, Javascript)</li>
			</ul>
		</resume>
		<plan></plan>
		<lieu>Luminy</lieu>
		
		<ref-intervenant ref="massat"></ref-intervenant>
	</unite>
	
	<unite id="ENSINCU31">
		<nom>Systèmes hétérogènes</nom>
		<nbCredit>3</nbCredit>
		<resume><p>Les parties magistrales de l'enseignement seront l'occasion d'aborder notamment les aspects suivants :</p>
			<ul>
				<li>Introduction aux métiers et organisation des Systèmes d'Information (DSI, AMO, MOE, architectes, exploitants...)</li>
				<li>Introduction aux stratégies d'entreprises autour de leurs systèmes d'information (plan de continuité d'activité, plan de reprise d'activité, plan de continuité informatique...)</li>
				<li>Introduction à la conception et à l'évolution de systèmes d'information (recueil et analyse de l'existant, des besoins et contraintes, scénarii, rédaction de cahier des charges...)
</li>
				<li>Découvertes des technologies liées à la disponibilité et haute disponibilité des données informatiques (réseaux de stockage - SAN, NAS -, virtualisation...)</li>
				<li>Découverte des architectures de disponibilité et haute disponibilité des SI (analyse des besoins, conception, cloud computing...)</li>
				<li>Approfondissement des savoirs autour des réseaux de transferts de données d'entreprises (routage, réseaux privés virtuels...)</li>
				<li>Découverte des infrastructures de services des réseaux de données</li>
			</ul>
			<p><b>Pre-Requis</b></p>
			<ul>
				<li>Connaissances fondamentales en utilisation et administration des systèmes d'exploitation de type serveurs (Microsoft, Linux).</li>
			</ul>
		</resume>
		<plan></plan>
		<lieu>Luminy</lieu>
		
		<ref-intervenant ref="agopian"></ref-intervenant>
	</unite>
	
	<unite id="ENSINCU67">
		<nom>Projet d'entreprise</nom>
		<nbCredit>3</nbCredit>
		<resume><p>L'objet de cet enseignement est de présenter un projet de création et de développementd'entreprise. Le but est de donner une vision horizontale des différents aspects à examiner pour se lancerdans une création d'entreprise, sans la complétude verticale donnée par exemple par un cours de type« école de commerce » sur l'aspect marché. Une vision de Business Plan pourra ainsi être acquise à la finde cet enseignement.</p></resume>
		<plan></plan>
		<lieu>Luminy</lieu>
		
		<ref-intervenant ref="godard"></ref-intervenant>
	</unite>
	
	<unite id="ENSINCU32">
		<nom>Genie Logiciel</nom>
		<nbCredit>6</nbCredit>
		<resume>Processus logiciel, Gestion de projet, Spécification et conception, Design patterns</resume>
		<plan></plan>
		<lieu>Luminy</lieu>
		
		<ref-intervenant ref="novelli"></ref-intervenant>
	</unite>
	
	<unite id="ENSINCU33">
		<nom>Genie Logiciel</nom>
		<nbCredit>6</nbCredit>
		<resume>Processus logiciel, Gestion de projet, Spécification et conception, Design patterns</resume>
		<plan></plan>
		<lieu>Luminy</lieu>
		
		<ref-intervenant ref="novelli"></ref-intervenant>
	</unite>
	
	<unite id="ENSINCU34">
		<nom>Sécurité internet et réseau</nom>
		<nbCredit>6</nbCredit>
		<resume><p>Le cours aborde la sécurité de l'information sous deux aspects :</p>
			<ul>
				<li></li>
			</ul>
		</resume>
		<plan></plan>
		<lieu>Luminy</lieu>
		
		<ref-intervenant ref="novelli"></ref-intervenant>
	</unite>
	
	<unite id="ENSINCU35">
		<nom>Genie Logiciel</nom>
		<nbCredit>6</nbCredit>
		<resume>Processus logiciel, Gestion de projet, Spécification et conception, Design patterns</resume>
		<plan></plan>
		<lieu>Luminy</lieu>
		
		<ref-intervenant ref="novelli"></ref-intervenant>
	</unite>
	
	<unite id="ENSINDU3">
		<nom>Genie Logiciel</nom>
		<nbCredit>6</nbCredit>
		<resume>Processus logiciel, Gestion de projet, Spécification et conception, Design patterns</resume>
		<plan></plan>
		<lieu>Luminy</lieu>
		
		<ref-intervenant ref="novelli"></ref-intervenant>
	</unite>
	
	<unite id="ENSINDU4">
		<nom>Genie Logiciel</nom>
		<nbCredit>6</nbCredit>
		<resume>Processus logiciel, Gestion de projet, Spécification et conception, Design patterns</resume>
		<plan></plan>
		<lieu>Luminy</lieu>
		
		<ref-intervenant ref="novelli"></ref-intervenant>
	</unite>

	<unite id="ENSINAU1">
		<nom>Genie Logiciel</nom>
		<nbCredit>6</nbCredit>
		<resume>Processus logiciel, Gestion de projet, Spécification et conception, Design patterns</resume>
		<plan></plan>
		<lieu>Luminy</lieu>
		
		<ref-intervenant ref="novelli"></ref-intervenant>
	</unite>
