=== magben2/ProjetXML/SiteMaster/complement-donnees.dtd
<?xml version="1.0" encoding="iso-8859-1"?>

<!ELEMENT elements (element+)>
<!ELEMENT element (#PCDATA)>
<!ATTLIST element ref NMTOKENS #REQUIRED>
<!ATTLIST element type CDATA #REQUIRED>

=== magben2/ProjetXML/complement-donnees.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE elements SYSTEM "complement-donnees.dtd">

<!-- Données complémentaires utilisées pour générer le fichier master-gen.xml -->
<elements>
	<element ref="IN18" type="site">http://jean-luc.massat.perso.luminy.univ-amu.fr/ens/</element>
	<element ref="IN13794" type="site">http://pageperso.lif.univ-mrs.fr/~frederic.olive/</element>
	<element ref="IN2563" type="site">http://pageperso.lif.univ-mrs.fr/~emmanuel.godard/</element>
	<element ref="IN3524" type="site">http://pageperso.lif.univ-mrs.fr/~denis.lugiez/</element>
	<element ref="IN9224" type="site">http://pageperso.lif.univ-mrs.fr/~remi.morin/</element>
	<element ref="IN9941" type="site">http://pageperso.lif.univ-mrs.fr/~frederic.bechet/</element>
	<element ref="IN10388" type="site">http://pageperso.lif.univ-mrs.fr/~benoit.favre/</element>
	<element ref="IN6213" type="site">http://pageperso.lif.univ-mrs.fr/~arnaud.labourel/</element>
	<element ref="IN7722" type="site">http://pageperso.lif.univ-mrs.fr/~noel.novelli/</element>
	<element ref="IN16209" type="site">http://pageperso.lif.univ-mrs.fr/~liva.ralaivola/doku.php/</element>
	<element ref="IN8086" type="site">http://pageperso.lif.univ-mrs.fr/~yann.vaxes/</element>
	
	<element ref="PRSIN4T0" type="lieu_parc">Luminy_Saint-Jérome</element>
	<element ref="PRSIN5A0" type="lieu_parc">Luminy</element>
	<element ref="PRSIN5B1" type="lieu_parc">Saint-Jérome</element>
	<element ref="PRSIN5B2" type="lieu_parc">Luminy</element>
	<element ref="PRSIN5B3" type="lieu_parc">Saint-Jérome</element>
	<element ref="PRSIN5C1" type="lieu_parc">Luminy</element>
	<element ref="PRSIN5C2" type="lieu_parc">Luminy</element>
	<element ref="PRSIN5D0" type="lieu_parc">Saint-Jérome</element>
	<element ref="PRSIN5E1" type="lieu_parc">Luminy</element>
	<element ref="PRSIN5E2" type="lieu_parc">Luminy</element>
	<element ref="PRSIN5F0" type="lieu_parc">Luminy</element>
	<element ref="PRSIN5G0" type="lieu_parc">Saint-Jérome</element>
</elements>
